config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :places
  resources :locations
  resources :categories
 mount API::Base => '/api'

  root 'places#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :places
  mount_uploader :photo , ImageUploader
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base


  def self.create_or_update_feedback (place_id, email, deviceID, message, rating_value, likes)

    @feedback = Feedback.where(deviceID: deviceID , place_id: place_id)

    if @feedback.present?
        # @feedback = Feedback.update( message: message, rating_value: rating_value)
        @feedback.update_all( message: message, rating_value: rating_value)

    else
      @feedback = Feedback.create!(place_id: place_id, email: email, deviceID: deviceID, message: message, rating_value: rating_value, likes: likes)
    end
  end

  def self.get_feedback_messages(place_id)
  @feedback = Feedback.select(:message).where(place_id: place_id).order('id DESC')
  end

  def self.get_rating(place_id)
  @feedback = Feedback.where(place_id: place_id).average(:rating_value)
  end

  def self.get_no_of_likes (place_id)
  @feedback = Feedback.where(place_id: place_id, likes: true).count()
  end

  def self.update_likes (place_id,deviceID)
    @feedback = Feedback.where(deviceID: deviceID , place_id: place_id)

    if @feedback.present?
      @feedback.update_all(likes:true)
    else
      @feedback = Feedback.create!(place_id: place_id,deviceID: deviceID, likes: true )
    end

  end
end

app/models/location.rb
class Location < ActiveRecord::Base

 # belongs_to :category
  has_many :places

end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :category
  belongs_to :location

  mount_uploader :photo , ImageUploader


  def self.find_by_category(category)
    Place.where(category_id:  category)
  end

  def self.find_by_location(location,category)
    Place.where(location_id: location ,category_id: category)
  end

  def self.find_by_search_text(search_text)
    Place.where("place_name LIKE ?","%#{search_text}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_filter :authenticate_user! , except: [:index, :show]

  def index
    @categories = Category.all
  end

def show
  @category = Category.find(params[:id])
end
  def new
    @category = Category.new
  end

  def create
    @category = Category.new (category_params)
    if @category.save!
      redirect_to @category, notice: 'Category was successfully added.'

    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end
def update
@category = Category.find(params[:id])
if @category.update(category_params)
  redirect_to categories_path , notice: 'Category updated successfully'
else
  redirect_to edit_category_path
end
end
  private
  def category_params
    params.require(:category).permit(:category_name,:photo)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save!
      redirect_to locations_path
    else
      redirect_to new_location_path
    end
  end

def edit
  @location = Location.find(params[:id])
end

def update
  @location = Location.find(params[:id])
if @location.update(location_params)
  redirect_to locations_path
else
  redirect_to edit_location_path
end
end


  private
  def location_params
    params.require(:location).permit(:id,:location_name)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index

    @places = Place.all

  end

  def show
    @place = Place.find(params[:id])
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save!
      redirect_to @place, notice: 'place was successfully added.'

    else
      render :new
    end
  end
def edit
  @place = Place.find(params[:id])
end
def update
  @place = Place.find(params[:id])
  if @place.update(place_params)
    redirect_to places_path, notice: 'Place details updated.'
  else
    redirect_to edit_place_path

  end
end
  def destroy
  end


end

def place_params
  params.require(:place).permit(:place_name, :location_id, :category_id, :address,:latitude ,:longitude, :photo, :short_description, :contact_number, :contact_person)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/categories/_form.html.erb
<%= semantic_form_for @category do |f| %>
<%= f.inputs do %>
<%= f.input :category_name %>
<%= f.input :photo , as: :file %>
<%end%>

<%= f.actions do %>
    <%= f.action :submit, :as => :input %>
<% end %>

<% end %>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>
<div class="row">
<div class="small-2 columns">Category</div>
<div class="small-4 columns">Photo</div>
<div class="small-4 columns"></div>
</div>
<hr />
  <% @categories.each do |category| %>

  <div class="row">
<div class="small-2 columns"><%= category.category_name %></div>

<div class="small-4 columns"><%= image_tag category.photo.to_s %></div>
<div class="small-1 columns">
	<%= link_to 'Show', category %>|
	<%= link_to 'Edit', edit_category_path(category) %>|
	<%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
</div>
  <% end %>
<%= link_to 'New Category', new_category_path%>

app/views/categories/new.html.erb
<h1>Add New Category</h1>

<%= render 'form'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<div class="row">	
	
	  <%= yield %>
	
	 
</div>
   

  </body>
</html>

app/views/locations/_form.html.erb
<%=semantic_form_for @location do |f| %>
<%=f.input :location_name %>
<%=f.submit%>
<%end%>

app/views/locations/edit.html.erb
<%= render 'form' %>
<%= link_to 'All Locations' ,locations_path %>

app/views/locations/index.html.erb
<h1>Locations#index</h1>
<p>Find me in app/views/locations/index.html.erb</p>
<table>
  <thead>
  <tr>
    <th>Location Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @locations.each do |location| %>
      <tr>
        <td><%= location.location_name %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'New Location', new_location_path%> 

app/views/locations/new.html.erb
<h1>Locations#new</h1>
<p>Find me in app/views/locations/new.html.erb</p>
<%= render 'form'%>
<%= link_to 'All Locations',locations_path %>

app/views/locations/show.html.erb
<h1>Locations#show</h1>
<p>Find me in app/views/locations/show.html.erb</p>

app/views/places/_form.html.erb
<%= semantic_form_for @place ,html:  {multipart: true} do |f| %>
    <%= f.inputs do %>
        <%= f.input :place_name %>
        <%= f.input :category_id, as: :select , :collection => Category.pluck(:category_name,:id) %>
        <%= f.input :location_id, as: :select , :collection => Location.pluck(:location_name,:id)%>
        <%= f.input :short_description , as: :text ,rows_size: 3 %>
        <%= f.input :address %>
        <%= f.input :latitude %>
        <%= f.input :longitude %>
        <%= f.input :contact_number , label: 'Phone' %>
        <%= f.input :contact_person %>
        <%= f.input :photo, as: :file%>


    <% end %>

    <%= f.actions do %>
        <%= f.action :submit, :as => :input %>
    <% end %>
<% end %>

app/views/places/edit.html.erb
<%= render 'form'%>

app/views/places/index.html.erb
<h1>Places#index</h1>
<p>Find me in app/views/locations/index.html.erb</p>


<div class="row">
<div class="small-2 columns">Name</div>
<div class="small-1 columns">Location</div>
<div class="small-2 columns">Address</div>
<div class="small-2 columns">Description</div>
<div class="small-4 columns">Photo</div>
<div class="small-1 columns"></div>
</div>
<hr />
  <% @places.each do |place| %>
  
  <div class="row">
<div class="small-2 columns"><%= place.place_name %></div>
<div class="small-1 columns"><%= place.location.location_name %></div>
<div class="small-2 columns"><%= place.address %></div>
<div class="small-2 columns"><%= place.short_description %></div>
<div class="small-4 columns"><%= image_tag place.photo.to_s %></div>
<div class="small-1 columns">
	<%= link_to 'Show', place %>|
	<%= link_to 'Edit', edit_place_path(place) %>|
	<%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %>	
</div>
</div>    
  <% end %> 
<%= link_to 'New Place', new_place_path%>

app/views/places/new.html.erb
<%= render 'form'%>

app/views/places/show.html.erb
<table border="all">
<tr>
<td colspan="20px">Place Name </td>
<td> <%= @place.place_name%> </td>
</tr>
</table